# Generated by Django 2.1.3 on 2018-11-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField(max_length=100, verbose_name='Database Name')),
                ('size', models.IntegerField(help_text='Keep in mind that database size must be specified in GB.', verbose_name='Database Size')),
                ('application_name', models.CharField(max_length=100, verbose_name='Application Name')),
                ('team_distribution_list', models.CharField(max_length=100)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('request_completed', models.NullBooleanField()),
                ('log_message', models.CharField(max_length=2000, null=True)),
                ('is_database_created', models.NullBooleanField(verbose_name='Database Created')),
                ('dba_approval', models.NullBooleanField(verbose_name='DBA Approval')),
                ('manager_approval', models.NullBooleanField(verbose_name='Manager approval')),
                ('manager_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Manager approval date')),
                ('last_email_sent', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('is_added_application_repository', models.NullBooleanField(verbose_name='Added to application repository')),
                ('manager_approval_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_database_manager_approval', to=settings.AUTH_USER_MODEL)),
                ('server_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Servers')),
                ('user_requestor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='new_database_user_requestor', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Versions')),
            ],
            options={
                'verbose_name': 'Database Request',
                'verbose_name_plural': 'Database Requests',
            },
        ),
    ]
