# Generated by Django 2.1.3 on 2018-12-21 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdatabase',
            name='server_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Servers', verbose_name='Server Name'),
        ),
        migrations.AlterField(
            model_name='newdatabase',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='server.Versions', verbose_name='Version'),
        ),
    ]
