# Generated by Django 2.1.3 on 2018-11-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100, verbose_name='Server name')),
                ('tcp_port', models.CharField(max_length=5, verbose_name='TCP Port')),
                ('role', models.CharField(choices=[('PRODUCTION', 'PRODUCTION'), ('DEVELOPMENT', 'DEVELOPMENT'), ('TEST', 'TEST'), ('MANAGEMENT', 'MANAGEMENT'), ('REPORTING', 'REPORTING')], max_length=30, verbose_name='Server Role')),
                ('Node1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Node 01')),
                ('Node2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Node 02')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edition')),
                ('service_pack', models.CharField(blank=True, max_length=5, null=True, verbose_name='Service Pack')),
                ('cummulative_update', models.CharField(blank=True, max_length=5, null=True, verbose_name='Cummulative Update')),
                ('always_on_enabled', models.NullBooleanField(verbose_name='Always ON Enabled')),
                ('failover_clustering_enabled', models.NullBooleanField(verbose_name='Failover Clustering Enabled')),
                ('is_visible', models.NullBooleanField(verbose_name='Visible')),
                ('is_active', models.NullBooleanField(default=1, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='SQL Server Version')),
                ('is_active', models.NullBooleanField(verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Version',
                'verbose_name_plural': 'Versions',
            },
        ),
        migrations.AddField(
            model_name='servers',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='server.Versions'),
        ),
    ]
